application:
  name: urlshortener
  project: urlshortener
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: urlshortener
    paths:
    - /*
