version: '2'
services:
  postgresql:
    image: postgres:11
    ports:
      - "${DATABASE_TEST_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

volumes:
  postgres-data:
